### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by plantain-00** [plantain-00/SubsNoti#143]
## todo

- [ ] angular2 branch
- [ ] set theme's ownership
- [ ] tags
- [ ] native

## finished

- [x] improve UI
- [x] fix log out
- [x] replace http with https for images & limit size of image
- [x] upload file & copy image
- [x] queue of commands
- [x] add expanded state of theme
- [x] change position when collapsed and editing finished
- [x] store summary of theme in theme model
- [x] use variable and template in documents
- [x] the content of theme can be markdown, link of html, drag and drop image
- [x] update document of frontends
- [x] enable http2
- [x] use `submodule` to share code between frontends and backends
- [x] remove lodash for backends and frontends, use ES6 only
- [x] oauth2 api tests
- [x] show application's information at authorization page
- [x] record and show the moment of an access token last useds
- [x] remove access tokens when application removed
- [x] login page can handle parameters of appId, scope, random string named state
- [x] after login, redirect to `/oauth/authorize` page to let user to accept the scopes, then server redirects to the redirectUri with code and state
- [x] `/oauth/access_token` interface can accept code, state, appId, appSecret, and creates an access_token with scopes for the application and current user, as response
- [x] get authorized applications page
- [x] revoke an application
- [x] get access tokens page
- [x] create an access token page
- [x] update an access token page
- [x] delete an access token
- [x] get registered applications page
- [x] register an application page
- [x] update an application page
- [x] delete an application
- [x] reset client secret
- [x] add https
- [x] auto deploy
- [x] make `push` in `/themes` namespace and an organization maps a room
- [x] add api `/version`
- [x] move html router into a new directory
- [x] add design document, the structure of the project, with the `dot` file
- [x] extract document site(use nginx to serve)
- [x] test the safety with some free tools
- [x] fix document in response
- [x] clean watch scripts
- [x] separate `make` task to a frontend and a backend tasks
- [x] explore baseline test
- [x] use nginx rather than nodejs' static middleware
- [x] add `faker` lib
- [x] replace settings in various environment with `Map`
- [x] create types for all responses
- [x] finish the remaining tests of apis
  - [x] upload avatar
  - [x] update user's avatar
